<?php
/**
 * Web installer for the AI Pro Time-Sharing PHP app.
 *
 * Standalone on purpose — does NOT use bootstrap.php (which selects a DB that may not
 * exist yet). Reads config.local.php (if present) to pre-fill the connection form, and
 * writes config.local.php when the user saves new settings.
 *
 * SECURITY: delete or restrict access to this file after setup.
 */
declare(strict_types=1);
session_start();

const SCHEMA_FILE = __DIR__ . '/database/schema.sql';
const SEED_FILE   = __DIR__ . '/database/seed.sql';
const LOCAL_CFG   = __DIR__ . '/config.local.php';

if (empty($_SESSION['install_csrf'])) {
    $_SESSION['install_csrf'] = bin2hex(random_bytes(32));
}
$csrf = $_SESSION['install_csrf'];

function h(?string $s): string
{
    return htmlspecialchars($s ?? '', ENT_QUOTES, 'UTF-8');
}

// ── Read current config (config.local.php if exists, else defaults) ────────
function read_local_cfg(): array
{
    if (file_exists(LOCAL_CFG)) {
        $v = require LOCAL_CFG;
        if (is_array($v)) { return $v; }
    }
    return [];
}

function write_local_cfg(string $host, string $port, string $name, string $user, string $pass, string $appBase): bool
{
    $tpl = "<?php\n// Auto-generated by install.php — update via the installer, not manually.\nreturn [\n"
         . "    'host'     => " . var_export($host, true) . ",\n"
         . "    'port'     => " . var_export($port, true) . ",\n"
         . "    'name'     => " . var_export($name, true) . ",\n"
         . "    'user'     => " . var_export($user, true) . ",\n"
         . "    'pass'     => " . var_export($pass, true) . ",\n"
         . "    'app_base' => " . var_export($appBase, true) . ",\n"
         . "];\n";
    return (bool) file_put_contents(LOCAL_CFG, $tpl);
}

/** Auto-detect APP_BASE the same way bootstrap.php does (for display in the form). */
function detect_app_base(): string
{
    $projectRoot    = str_replace('\\', '/', __DIR__);
    $scriptFilename = str_replace('\\', '/', $_SERVER['SCRIPT_FILENAME'] ?? '');
    $scriptName     = $_SERVER['SCRIPT_NAME'] ?? '';
    $relScript      = str_starts_with($scriptFilename, $projectRoot . '/')
                        ? substr($scriptFilename, strlen($projectRoot) + 1)
                        : '';
    if ($relScript !== '' && str_ends_with($scriptName, '/' . $relScript)) {
        return substr($scriptName, 0, -strlen('/' . $relScript));
    }
    $docRoot = str_replace('\\', '/', $_SERVER['DOCUMENT_ROOT'] ?? '');
    return rtrim(substr($projectRoot, strlen($docRoot)), '/');
}

/** New PDO using explicit settings; $withDb selects the app database. */
function make_pdo(string $host, string $port, string $name, string $user, string $pass, bool $withDb): PDO
{
    $dsn = $withDb
        ? "mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4"
        : "mysql:host={$host};port={$port};charset=utf8mb4";
    return new PDO($dsn, $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
}

/** Run a whole .sql file via exec() (handles multi-statement files). */
function run_sql_file(PDO $pdo, string $path): void
{
    $sql = file_get_contents($path);
    if ($sql === false) { throw new RuntimeException('อ่านไฟล์ไม่ได้: ' . basename($path)); }
    $pdo->exec($sql);
}

// ── Pre-fill form from stored local config ─────────────────────────────────
$saved = read_local_cfg();
// Production default is port 3306; WAMP dev is 3307. Pre-fill 3306 when no local config exists.
$fHost    = $saved['host']     ?? '127.0.0.1';
$fPort    = $saved['port']     ?? '3306';
$fName    = $saved['name']     ?? 'rvc_apts';
$fUser    = $saved['user']     ?? 'root';
$fPass    = $saved['pass']     ?? '';
$fAppBase = $saved['app_base'] ?? '';

// ── Handle POST ────────────────────────────────────────────────────────────
$flashOk    = null;
$flashErr   = null;
$installOk  = false;
$userCount  = 0;
$testResult = null;   // null | 'ok' | 'err'
$testMsg    = '';

$phpOk      = PHP_VERSION_ID >= 80000;
$pdoMysqlOk = extension_loaded('pdo_mysql');
$filesOk    = is_readable(SCHEMA_FILE) && is_readable(SEED_FILE);
$writeable  = is_writable(__DIR__) || file_exists(LOCAL_CFG);

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!hash_equals($csrf, $_POST['csrf'] ?? '')) {
        $flashErr = 'โทเคนความปลอดภัยไม่ถูกต้อง กรุณาโหลดหน้านี้ใหม่';
    } else {
        // Read form values
        $fHost    = trim($_POST['db_host']    ?? $fHost);
        $fPort    = trim($_POST['db_port']    ?? $fPort);
        $fName    = trim($_POST['db_name']    ?? $fName);
        $fUser    = trim($_POST['db_user']    ?? $fUser);
        $fPass    = $_POST['db_pass']         ?? $fPass;
        $fAppBase = rtrim(trim($_POST['app_base'] ?? $fAppBase), '/');

        if ($fHost === '' || $fPort === '' || $fName === '' || $fUser === '') {
            $flashErr = 'กรุณากรอกข้อมูลการเชื่อมต่อให้ครบถ้วน';
        } else {
            $action = $_POST['action'] ?? 'test';

            // Step 1: write config.local.php
            if (!write_local_cfg($fHost, $fPort, $fName, $fUser, $fPass, $fAppBase)) {
                $flashErr = 'เขียนไฟล์ config.local.php ไม่ได้ — ตรวจสอบสิทธิ์การเขียนในโฟลเดอร์แอป';
            } else {
                // Step 2: test connection
                try {
                    $pdo = make_pdo($fHost, $fPort, $fName, $fUser, $fPass, false);
                    $testResult = 'ok';

                    if ($action === 'install') {
                        if (!$phpOk || !$pdoMysqlOk || !$filesOk) {
                            $flashErr = 'ระบบยังไม่พร้อม กรุณาแก้ไขรายการที่ล้มเหลวก่อน';
                        } else {
                            // Check if DB exists + has data
                            $stmt = $pdo->prepare('SELECT COUNT(*) FROM information_schema.SCHEMATA WHERE SCHEMA_NAME = ?');
                            $stmt->execute([$fName]);
                            $dbExists = (bool) $stmt->fetchColumn();
                            $seeded   = false;
                            if ($dbExists) {
                                try {
                                    $userCount = (int) make_pdo($fHost, $fPort, $fName, $fUser, $fPass, true)->query('SELECT COUNT(*) FROM users')->fetchColumn();
                                    $seeded    = $userCount > 0;
                                } catch (Throwable) {}
                            }

                            $reinstall = isset($_POST['reinstall']);
                            if ($dbExists && $seeded && !$reinstall) {
                                $flashErr = 'ฐานข้อมูลมีข้อมูลอยู่แล้ว หากต้องการติดตั้งใหม่ กรุณาติ๊กยืนยัน';
                            } else {
                                try {
                                    if ($dbExists && $reinstall) {
                                        $pdo->exec('DROP DATABASE IF EXISTS `' . $fName . '`');
                                    }
                                    run_sql_file($pdo, SCHEMA_FILE);
                                    run_sql_file(make_pdo($fHost, $fPort, $fName, $fUser, $fPass, true), SEED_FILE);
                                    $userCount = (int) make_pdo($fHost, $fPort, $fName, $fUser, $fPass, true)->query('SELECT COUNT(*) FROM users')->fetchColumn();
                                    $installOk = true;
                                    $flashOk   = 'ติดตั้งฐานข้อมูลสำเร็จ! นำเข้าโครงสร้างและข้อมูลตัวอย่างเรียบร้อยแล้ว';
                                } catch (Throwable $e) {
                                    $flashErr = 'ติดตั้งไม่สำเร็จ: ' . $e->getMessage();
                                }
                            }
                        }
                    } else {
                        $flashOk = 'เชื่อมต่อฐานข้อมูลสำเร็จ! บันทึก config.local.php เรียบร้อยแล้ว';
                    }
                } catch (Throwable $e) {
                    $testResult = 'err';
                    $testMsg    = $e->getMessage();
                    $flashErr   = 'เชื่อมต่อฐานข้อมูลไม่ได้: ' . $e->getMessage();
                }
            }
        }
    }
}

// Current connection probe (for the status section, after any POST)
$connOk    = false;
$connError = null;
$dbExists  = false;
$seeded    = false;
$userCount_probe = 0;
try {
    $probePdo = make_pdo($fHost, $fPort, $fName, $fUser, $fPass, false);
    $connOk   = true;
    $stmt2    = $probePdo->prepare('SELECT COUNT(*) FROM information_schema.SCHEMATA WHERE SCHEMA_NAME = ?');
    $stmt2->execute([$fName]);
    $dbExists = (bool) $stmt2->fetchColumn();
    if ($dbExists) {
        try {
            $userCount_probe = (int) make_pdo($fHost, $fPort, $fName, $fUser, $fPass, true)->query('SELECT COUNT(*) FROM users')->fetchColumn();
            $seeded = $userCount_probe > 0;
        } catch (Throwable) {}
    }
} catch (Throwable $e) {
    $connError = $e->getMessage();
}

function check_row(bool $ok, string $label, string $detail = ''): string
{
    $icon = $ok
        ? '<i class="bi bi-check-circle-fill" style="color:#059669"></i>'
        : '<i class="bi bi-x-circle-fill" style="color:#DC2626"></i>';
    $d = $detail !== '' ? '<span style="color:var(--bs-tertiary-color);font-size:12px;margin-left:6px">' . h($detail) . '</span>' : '';
    return '<div style="display:flex;align-items:center;gap:8px;padding:7px 0;font-size:13px">'
        . $icon . '<span>' . h($label) . '</span>' . $d . '</div>';
}
?>
<!DOCTYPE html>
<html lang="th">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ติดตั้งระบบ — AI Pro Time-Sharing</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Thai:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
<link href="assets/app.css?v=<?= @filemtime(__DIR__ . '/assets/app.css') ?>" rel="stylesheet">
<style>
.section-card { border:1px solid var(--bs-border-color);border-radius:10px;padding:18px 20px;margin-bottom:16px }
.section-title { font-weight:700;font-size:12px;color:var(--bs-secondary-color);text-transform:uppercase;letter-spacing:.04em;margin-bottom:10px }
.input-row { display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:10px }
.input-row-3 { display:grid;grid-template-columns:2fr 1fr;gap:10px;margin-bottom:10px }
label.lbl { font-size:11px;font-weight:600;color:var(--bs-secondary-color);display:block;margin-bottom:4px }
</style>
</head>
<body>
<div class="auth-bg">
  <div class="auth-card auth-card-wide page-anim" style="max-width:580px">
    <div style="display:flex;align-items:center;gap:12px;margin-bottom:20px">
      <div class="logo-icon" style="width:44px;height:44px;border-radius:11px">
        <i class="bi bi-hdd-stack-fill" style="color:white;font-size:18px"></i>
      </div>
      <div>
        <h5 style="font-weight:700;color:#0F172A;margin:0">ติดตั้งระบบ</h5>
        <p style="color:var(--bs-secondary-color);font-size:13px;margin:0">AI Pro Time-Sharing — วิทยาลัย RVC</p>
      </div>
    </div>

    <?php if ($flashErr): ?>
      <div class="alert alert-danger" style="font-size:13px;display:flex;gap:8px;align-items:flex-start">
        <i class="bi bi-x-circle-fill" style="margin-top:1px;flex-shrink:0"></i>
        <span><?= h($flashErr) ?></span>
      </div>
    <?php elseif ($flashOk): ?>
      <div class="alert alert-success" style="font-size:13px;display:flex;gap:8px;align-items:flex-start">
        <i class="bi bi-check-circle-fill" style="margin-top:1px;flex-shrink:0"></i>
        <span><?= h($flashOk) ?></span>
      </div>
    <?php endif; ?>

    <?php if ($installOk): ?>
      <!-- ── Success state ───────────────────────────────────────────────── -->
      <div class="section-card" style="background:var(--bs-secondary-bg)">
        <div style="font-weight:700;font-size:13px;margin-bottom:8px">บัญชีสำหรับเข้าสู่ระบบ (รหัสผ่านทุกบัญชี: <code>Passw0rd!</code>)</div>
        <div style="font-size:13px;line-height:2">
          <div><i class="bi bi-shield-lock me-1" style="color:#2563EB"></i><strong>ผู้ดูแลระบบ:</strong> admin@rvc.ac.th</div>
          <div><i class="bi bi-person me-1" style="color:#2563EB"></i><strong>นักศึกษา (ตัวอย่าง):</strong> somchai@rvc.ac.th</div>
        </div>
      </div>
      <div style="background:#FEF2F2;border-radius:8px;padding:10px 14px;margin-bottom:16px;font-size:12px;color:#991B1B;display:flex;gap:8px;align-items:flex-start">
        <i class="bi bi-exclamation-triangle-fill" style="margin-top:1px;flex-shrink:0"></i>
        <span>เพื่อความปลอดภัย โปรด <strong>ลบหรือจำกัดการเข้าถึงไฟล์ <code>install.php</code></strong> หลังติดตั้งเสร็จ</span>
      </div>
      <a href="login.php" class="btn btn-primary w-100" style="background:linear-gradient(90deg,#2563EB,#0EA5E9);border:none;font-weight:600;padding:11px">
        <i class="bi bi-box-arrow-in-right me-2"></i>ไปหน้าเข้าสู่ระบบ
      </a>

    <?php else: ?>
      <!-- ── DB Config Form ──────────────────────────────────────────────── -->
      <form method="post" id="mainForm">
        <input type="hidden" name="csrf" value="<?= h($csrf) ?>">

        <div class="section-card">
          <div class="section-title"><i class="bi bi-server me-1"></i>ตั้งค่าการเชื่อมต่อฐานข้อมูล</div>

          <div class="input-row-3">
            <div>
              <label class="lbl" for="db_host">โฮสต์</label>
              <input id="db_host" name="db_host" class="form-control form-control-sm" value="<?= h($fHost) ?>" placeholder="127.0.0.1" required style="font-size:13px">
            </div>
            <div>
              <label class="lbl" for="db_port">พอร์ต</label>
              <input id="db_port" name="db_port" class="form-control form-control-sm" value="<?= h($fPort) ?>" placeholder="3306" required style="font-size:13px">
            </div>
          </div>
          <div style="margin-bottom:10px">
            <label class="lbl" for="db_name">ชื่อฐานข้อมูล</label>
            <input id="db_name" name="db_name" class="form-control form-control-sm" value="<?= h($fName) ?>" placeholder="rvc_apts" required style="font-size:13px">
          </div>
          <div class="input-row">
            <div>
              <label class="lbl" for="db_user">ผู้ใช้</label>
              <input id="db_user" name="db_user" class="form-control form-control-sm" value="<?= h($fUser) ?>" placeholder="root" required style="font-size:13px">
            </div>
            <div>
              <label class="lbl" for="db_pass">รหัสผ่าน</label>
              <input id="db_pass" name="db_pass" type="password" class="form-control form-control-sm" value="<?= h($fPass) ?>" placeholder="(ว่างถ้าไม่มี)" style="font-size:13px">
            </div>
          </div>

          <?php $autoBase = detect_app_base(); ?>
          <div style="margin-bottom:10px;border-top:1px solid var(--bs-border-color);padding-top:12px;margin-top:4px">
            <label class="lbl" for="app_base">
              URL Base (APP_BASE)
              <span style="font-weight:400;color:var(--bs-tertiary-color)"> — ปล่อยว่างเพื่อตรวจจับอัตโนมัติ</span>
            </label>
            <input id="app_base" name="app_base" class="form-control form-control-sm" value="<?= h($fAppBase) ?>" placeholder="<?= h($autoBase ?: '/') ?>" style="font-size:13px;font-family:monospace">
            <div style="font-size:11px;color:var(--bs-secondary-color);margin-top:4px">
              ตรวจจับอัตโนมัติได้: <code><?= h($autoBase ?: '/') ?></code>
              · ถ้า path CSS/JS ผิด ให้กรอก URL จริง เช่น <code>/web</code> หรือ <code>/</code> (ไม่ต้องมี / ท้าย)
            </div>
          </div>

          <?php if (!$writeable): ?>
            <div style="background:#FEF2F2;border-radius:6px;padding:8px 12px;font-size:12px;color:#991B1B;margin-top:6px">
              <i class="bi bi-exclamation-triangle-fill me-1"></i>โฟลเดอร์ไม่มีสิทธิ์เขียน — ไม่สามารถบันทึก config.local.php ได้ กรุณาเรียกใช้ <code>chmod a+w <?= h(__DIR__) ?></code>
            </div>
          <?php else: ?>
            <div style="font-size:11px;color:var(--bs-secondary-color);margin-top:8px">
              <i class="bi bi-info-circle me-1"></i>การตั้งค่าจะถูกบันทึกลงใน <code>config.local.php</code> โดยอัตโนมัติ
              <?php if (file_exists(LOCAL_CFG)): ?><span style="color:#059669">· มีไฟล์นี้อยู่แล้ว (โหลดค่าปัจจุบัน)</span><?php endif; ?>
            </div>
          <?php endif; ?>
        </div>

        <!-- ── System checks ──────────────────────────────────────────────── -->
        <div class="section-card">
          <div class="section-title"><i class="bi bi-clipboard-check me-1"></i>ตรวจสอบความพร้อม</div>
          <?= check_row($phpOk, 'PHP ' . PHP_VERSION, $phpOk ? '' : 'ต้องการ PHP 8.0 ขึ้นไป') ?>
          <?= check_row($pdoMysqlOk, 'ส่วนขยาย pdo_mysql', $pdoMysqlOk ? '' : 'ยังไม่ได้เปิดใช้งาน') ?>
          <?= check_row($filesOk, 'ไฟล์ schema.sql / seed.sql', $filesOk ? '' : 'ไม่พบในโฟลเดอร์ database/') ?>
          <?= check_row($connOk, 'เชื่อมต่อ ' . h($fHost) . ':' . h($fPort), $connOk ? 'ผู้ใช้ ' . h($fUser) : (string) $connError) ?>
          <?php if ($connOk): ?>
            <?= check_row(true, 'ฐานข้อมูล "' . h($fName) . '"', $dbExists ? ($seeded ? 'มีข้อมูล ' . $userCount_probe . ' ผู้ใช้' : 'มีอยู่ · ยังไม่มีตาราง') : 'ยังไม่มี — จะถูกสร้างใหม่') ?>
          <?php endif; ?>
        </div>

        <?php if (!$connOk): ?>
          <div style="background:#FFF7ED;border-radius:8px;padding:10px 14px;margin-bottom:14px;font-size:12px;color:#92400E;display:flex;gap:8px;align-items:flex-start">
            <i class="bi bi-info-circle-fill" style="margin-top:1px;flex-shrink:0"></i>
            <span>เชื่อมต่อฐานข้อมูลไม่ได้ กรุณาตรวจสอบค่าด้านบนแล้วกด <strong>ทดสอบการเชื่อมต่อ</strong><br>
            <span style="opacity:.8">Linux/cPanel มักใช้พอร์ต <strong>3306</strong> · WAMP ใช้ <strong>3307</strong> · ตรวจสอบชื่อ user และ password ให้ถูกต้อง</span></span>
          </div>
        <?php endif; ?>

        <?php if ($connOk && $dbExists && $seeded): ?>
          <label style="display:flex;gap:8px;align-items:flex-start;background:#FEF2F2;border-radius:8px;padding:10px 14px;margin-bottom:12px;font-size:12px;color:#991B1B;cursor:pointer">
            <input type="checkbox" name="reinstall" value="1" style="margin-top:2px">
            <span>ฐานข้อมูลมีข้อมูลอยู่แล้ว — ติ๊กเพื่อ <strong>ลบฐานข้อมูลเดิมทั้งหมดแล้วติดตั้งใหม่</strong> (ข้อมูลที่มีอยู่จะหายทั้งหมด)</span>
          </label>
        <?php endif; ?>

        <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">
          <button type="submit" name="action" value="test" class="btn btn-outline-secondary" style="font-size:13px;font-weight:600;padding:10px">
            <i class="bi bi-plug me-1"></i>ทดสอบการเชื่อมต่อ
          </button>
          <button type="submit" name="action" value="install" class="btn btn-primary" style="background:linear-gradient(90deg,#2563EB,#0EA5E9);border:none;font-size:13px;font-weight:600;padding:10px" <?= ($connOk && $phpOk && $pdoMysqlOk && $filesOk) ? '' : 'disabled' ?>>
            <i class="bi bi-download me-1"></i><?= ($connOk && $dbExists && $seeded) ? 'ติดตั้งใหม่' : 'ติดตั้งฐานข้อมูล' ?>
          </button>
        </div>
      </form>

      <p style="text-align:center;font-size:12px;color:var(--bs-tertiary-color);margin:14px 0 0">
        ติดตั้งแล้ว? <a href="login.php" style="color:#2563EB;font-weight:600;text-decoration:none">ไปหน้าเข้าสู่ระบบ</a>
        &nbsp;·&nbsp;<a href="migration.php" style="color:var(--bs-secondary-color);text-decoration:none">migration.php</a>
      </p>
    <?php endif; ?>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
